name: CI Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build and Test Spring Boot Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and run tests with Maven
        run: mvn clean install
        env:
          API_KEY: ${{secrets.API_KEY}}

      - name: Upload test results to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-re
